Restaurant.create(name: 'Santorini View', address: 'Canggu', category: 'italian')
Restaurant.create(name: 'Paris Croissant', address: 'Berawa', category: 'french')
Restaurant.create(name: 'Brussel Love', address: 'Seminyak', category: 'belgian')
Restaurant.create(name: 'China Star', address: 'Kuta', category: 'chinese')
Restaurant.create(name: 'Pizza Palace', address: 'Canggu', category: 'italian')
